all:
  hosts:
    pve_dev:
      ansible_host: pve-dev01.home
      ansible_port: 22
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/id_proxmox_ansible
      host_mgt_virtu_address: 10.0.1.11

    test:
      ansible_host: 10.0.10.99
      ansible_port: 22
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/id_ansible_homelab
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      sshd_permit_root_login: yes


  children:
    pve_hosts:
      hosts:
        pve_dev:
    vm_hosts:
      hosts:
        test:

